### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Kvodnon** [Sterc/modx-minify#22] opened 2017-10-31 08:00 UTC
MODX 2.7.1-pl
I'm trying to add a new group, but after clicking nothing happens.
Netwrok response:
`{"success":false,"message":"","total":1,"data":[{"id":"name","msg":"Key is not specified."}],"object":[]}`

**Comment by pepebe** [comment] 2017-12-19 21:00
Same here. MODX 2.6.0, latest Version (1.0.0pl)

**Comment by gpsietzema** [comment] 2017-12-20 12:39
@Kvodnon @pepebe I'm having difficulties reproducing it. Can you tell me a little more?
- Which browser are you using
- Quick list of other extras would be nice :)

**Comment by pepebe** [comment] 2018-01-02 09:24
@gpsietzema Hi, sorry for being late to the party. I'll look into this some more and give feedback.

**Comment by pepebe** [comment] 2018-01-09 10:24
Ok, I had another look at the problem and it seems to be a bit different. I even don't see the network response anymore. Reinstalled the whole package, but without any improvements on the situation. 

I'll open a new issue.

**Comment by messyp** [comment] 2018-02-22 23:19
Any update, just installed and not working for me

**Comment by joeke** [comment] 2018-05-03 11:51
We just released the 1.0.1 version: https://modx.com/extras/package/modxminify
Can you check if you still have the issue?

**Comment by Kvodnon** [comment] 2018-06-15 07:35
Problem solved, thanks.

**Comment by inreti-sb** [comment] 2019-04-06 07:21
Please close this issue. Thanks!

**Closed** 2019-11-12 21:55 UTC
Labels: bug
